import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Form from '../components/Form'
import withAuth from './hoc/withAuth'
import { ContentData } from '../types/user'
import {useEffect, useState } from 'react'
import { User } from '../types/user'
import PlayerCard from '../components/Cards/PlayerCard'
import CustomLoadingOverlay from '../components/Modals/CustomLoadingOverlay'

interface HomeProps {
  userID: string,
}

const fetchContent = async (userID: string): Promise<ContentData[]> => {
  try {
    // Fetch content based on the userID
    const response = await fetch(`/api/user/content_generated`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ userID: userID }),
    })
    const responseData: ContentData[] = await response.json();
    return responseData

  } catch (error) {
    console.error(error);
    throw new Error('Failed to fetch content');
  }
};

const Home: NextPage = () => {
  const [userID, setUserID] = useState<string>('');
  const [content, setContent] = useState<ContentData[] | null>(null);
  const [showPreparingOverlay, setPreparingOverlay] = useState(false);

  useEffect(() => {
    const user: User = JSON.parse(localStorage.getItem('user')!);

    if (user) {
      setUserID(user.id);
    }
  }, []);


  useEffect(() => {
    if (userID) {
      fetchContent(userID)
        .then((data) => {
          setContent(data)
        })
        .catch((error) => {
          console.error(error);
        });
    }
  }, [userID]);


  useEffect(()=>{
    console.log(showPreparingOverlay);
  },[showPreparingOverlay])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Readitforme</a>
        </h1>
        {/** Form to Create  */}
        <Form openOverlay={setPreparingOverlay} />
        {/** Generated Content Items */}
        <div className='py-8'>
          <div className='grid grid-cols-4 gap-4'>
            {content && (
              content.map((item, index) => (
                <PlayerCard data={item} key={index} />
              ))
            )}
          </div>
        </div>

        {/** Modal for preparing  */}
        <CustomLoadingOverlay visible={showPreparingOverlay}/>
      </main>
    </div>
  )
}

export default withAuth(Home)
